#pragma config(Sensor, port1,  rightbumper,    sensorVexIQ_Touch)
#pragma config(Sensor, port7,  leftbumper,     sensorVexIQ_Touch)
#pragma config(Motor,  motor5,          frontright,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          backright,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         frontleft,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         backleft,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
bool lastDirection;
bool currentDirection;
void drivetrain (int left, int right)
{
	motor[frontright] = right;
	motor[backright] = right;
	motor[frontleft] = left;
	motor[backleft] = left;
}

void do180 ()
{
	drivetrain (-50,-50);
	delay (200);
	drivetrain (-50,50);
	delay (1750);
	drivetrain (0,0); //stop motors after function ends
}

void rebound (int dir)
{
	drivetrain (-50,-50);
	delay (300);
	drivetrain (0,0);
	delay (200);
	drivetrain (dir * -30,dir * 30);
	delay (300);
}

task main()
{

	while (true){
		while ((SensorValue[rightbumper]) + (SensorValue[leftbumper]) <1)

		{
			drivetrain(50,50);
			delay (10);
		}
		if (SensorValue[rightbumper] == 1)
		{
			rebound (1);
			currentDirection = true;

		}
		else
		{
			rebound (-1);
			currentDirection = false;
		}
		if (currentDirection != lastDirection)//used to get out of corners. Leaves robot with no direction
		{
			do180();
		}
		lastDirection = currentDirection;//re-assigning a direction so robot knows where it is
	}
}
