#pragma config(Sensor, port1,  rightbumper,    sensorVexIQ_Touch)
#pragma config(Sensor, port7,  leftbumper,     sensorVexIQ_Touch)
#pragma config(Motor,  motor5,          frontright,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          backright,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         frontleft,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         backleft,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drivetrain (int left, int right)
{
	motor[frontright] = right;
	motor[backright] = right;
	motor[frontleft] = left;
	motor[backleft] = left;
}

task main()
{
	while (true){
		while ((SensorValue[rightbumper]) + (SensorValue[leftbumper]) <1)
		{
			drivetrain(50,50);
			delay (10);
		}
		drivetrain (-50,-50);
		delay (200);
		drivetrain (0,0);
		delay (200);
		drivetrain (50,-50);
		delay (200);
	}
}
