#pragma config(Sensor, port1,  rightbumper,    sensorVexIQ_Touch)
#pragma config(Sensor, port7,  leftbumper,     sensorVexIQ_Touch)
#pragma config(Motor,  motor5,          frontright,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          backright,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         frontleft,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         backleft,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
bool lastDirection;
bool currentDirection;
#include "headers/drivetrain.h"
#include "headers/do180.h"
#include "headers/rebound.h"

int thro;
int steering;
int joystick_thro_ch = 3;
int joystick_steering_ch = 2

task main()
{

	while (true)
	{
		if (vexRT[BtnLUp]==1)
		{
			thro = vexRT[joystick_thro_ch];
			steering = vexRT[joystick_steering_ch];

			drivetrain(thro + steering, thro - steering);
			delay(1);
		}
		else
		{
			while ((SensorValue[rightbumper]) + (SensorValue[leftbumper]) <1)

			{
				drivetrain(50,50);
				delay (10);
			}
			if (SensorValue[rightbumper] == 1)
			{
				rebound (1);
				currentDirection = true;

			}
			else
			{
				rebound (-1);
				currentDirection = false;
			}
			if (currentDirection != lastDirection)//used to get out of corners. Leaves robot with no direction
			{
				do180();
			}
			lastDirection = currentDirection;//re-assigning a direction so robot knows where it is
		}
	}
}
