#pragma config(Motor,  motor5,          foreStarboard, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          aftStarboard,  tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         forePort,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         aftPort,       tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// User defined variables
int thro;	//init the variables used to store values later
int heading;

int joystick_thro_ch = 3;	// Create fixed values that can be mapped later
int joystick_steer_ch = 2;

void drivetrain(int port, int starboard)	// make a function with two passed variables
{
	motor[foreStarboard] = starboard;	// write values to both motors on each side
	motor[aftStarboard] = starboard;
	motor[aftPort] = port;
	motor[forePort] = port;
}

task main()
{
	while(true)
	{
		thro = vexRT[joystick_thro_ch];
		heading = vexRT[joystick_steer_ch];

		drivetrain(thro + heading, thro - heading);
		delay(1);
	}
}
