#pragma config(Motor,  motor5,          foreStarboard, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          aftStarboard,  tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         forePort,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         aftPort,       tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// User included files
#include "/headers/drivetrain.h"	// Include the drivetrain.h file

// User defined variables
int thro;	//init the variables used to store values later
int heading;

int joystick_thro_ch = 3;	// Create fixed values that can be mapped later
int joystick_steer_ch = 2;

task main()	// Called once when the robot starts
{
	while(true)	// For as long as true
	{
		thro = vexRT[joystick_thro_ch];	// set thro to joystick_thro_ch
		heading = vexRT[joystick_steer_ch];	// set heading joystick_steer_ch

		drivetrain(thro + heading, thro - heading);	// Pass thro and heading values
		delay(1);	// Pause for CPU time
	}
}
